sudo: required

language: node_js

services:
  - docker

node_js:
  - node

branches:
  only:
    - master
    - develop

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=ringpartner/exchange-books
    - DOCKER_COMPOSE_VERSION=1.8.1

before_install:
  - docker-compose -p app up -d rabbitmq database consul
  - docker ps
  - sleep 15
  - docker-compose -p app up -d
  - docker ps
  - sleep 15

before_script:
  - docker exec -it app_api_1 npm run migrate
  - docker exec -it app_api_1 npm run seed

script:
  - docker exec -it app_api_1 npm run test

# before_deploy:
#   - npm install -g triton

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master

notifications:
  email: never
  slack:
    secure: "yEKzV8IMdKQBxUXnYAAKgAS8oG3Rhe2qLm7UPseCZvhsjFdTfulY1Ue3Y+DEJJEizn2q6GNt33wZ3lK6vY68tkCfSwp/wGH+peNoiR0BqHI7Via0HGgXWe/AoG0Zs0g9uAuP5FAAE0CwRU/qKhslzjurpuNZ9YTGy5h59KY0x1sJ7nBcWSJzFTY6HiNBLp408DBkfWOdBmH6ECai2RvzKpC/pqD/rnAQxF6sAC6G3iAhVhFvGLVCBRX/KMzwvaq3QVY59LMlwkIEric8tnjMdfrT7l5JTupjy26RBOwOxMT0cYJ/6bvFntIC2Y1yA2AeRkR/o8C76Ba4NWxEd0GE/JFeNTt8RSRtcJ/HmtkmtUGPoUSoLCgGf4E9/N3omHvgQSgOxPmF8iYgsipBkShSXHfklm08yrcbakjz3nwJ3GC5ryML4vpitQeNk5IUZMMFM3DAMDFAcy5rCreatxmQegDoBfNtkkxdEvokAV8eww9uLyDJRSso3Ri4Yh7vEjCzcnaqUQv65VLCZH/KOH5Lzky203Cd6bY4p4nQulEIjV4yNA7kB/JudUmMD6co6JNQj1mxHcy0unmC3AB/c8IFtO4+9KondMzdoEaoi8ozpvG6jn/6eKnoJhZ4R8YB5icPRD533UWo9fq/tu5xvYw6OS6aO9psixQJWuqYxfS/wtQ="
