sudo: required

language: node_js

services:
  - docker

node_js:
  - node

env:
  # You may want to update this to whatever the latest version is, or keep it
  # the same as your local machines. However, I have only tested it with 1.8.0+.
  # There should be a time in the future when this is not necessary - it is
  # explained in more detail below.
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:

  # Setup your application stack. You may need to tweak these commands if you
  # doing out-of-the-ordinary docker-compose builds.
  - docker-compose up -d

  # You will want this for logging. If one of your containers does not build for
  # whatever reason it's best to report that now before your tests start
  # otherwise it can be really tricky to debug why tests are failing sometimes.
  - docker ps

  - sleep 15

  # This is just our script to setup all the database tables and other fixtures
  # we need. You should remove this if it's not necessary or you have other
  # scripts handling this.
  # - docker/web/provision.sh

before_script:
  - docker-compose run api npm run migrate
  - docker-compose run api npm run seed
