sudo: required

language: node_js

services:
  - docker

node_js:
  - node

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:

  - docker-compose up -d

  # for logging
  - docker ps

  # give time for the database to spin up before migration
  - sleep 15

before_script:
  - docker-compose run api npm run migrate
  - docker-compose run api npm run seed

script:
  - docker-compose run api npm run test
