version: "2"

networks:
  back-tier:
    driver: bridge

services:

  database:
    hostname: database
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    networks:
      - back-tier
    expose:
      - 3306
    image: percona
    logging:
      driver: "json-file"
    mem_limit: 512m

  api:
    env_file: .env
    build: ./app
    command: npm run start
    environment:
      PORT: 3000
      MYSQL_HOST: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_HOST: "rabbitmq"
    mem_limit: 512m
    volumes:
      - ./app/lib:/opt/books/lib
    expose:
      - 3000
    networks:
      - back-tier
    logging:
      options:
        max-size: "1m"
        max-file: "2"
    links:
      - database

  rabbitmq:
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - back-tier
    image: ringpartner/rabbitmq-federation
    logging:
      driver: "json-file"
    mem_limit: 512m
