consul:
  image: autopilotpattern/consul
  restart: always
  dns:
    - 127.0.0.1
  ports:
    - "8500:8500"
  command: >
    /usr/local/bin/containerpilot
    /bin/consul agent -server
      -config-dir=/etc/consul
      -log-level=err
      -bootstrap-expect 1
      -ui-dir /ui

database:
  image: ringpartner/autopilot-percona
  environment:
    - PORT=3306
    - CONSUL_AGENT=1
    - CONSUL=consul
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=database
  links:
    - consul:consul
  restart: always

api:
  build: ./app
  environment:
    - NODE_PATH=/opt/app/lib
    - CONSUL_AGENT=1
    - CONSUL=consul
    - PORT=3000
    - APP_NAME=books-service
    - APP_VERISON=1.0.0
    - MYSQL_HOST=database
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=database
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    - RABBITMQ_HOST=rabbitmq
  ports:
    - "3000:3000"
  volumes:
    - ./app/lib:/opt/app/lib
  links:
    - rabbitmq:rabbitmq
    - database:database
    - consul:consul
  restart: always
  command: >
    /bin/containerpilot 
    /opt/app/node_modules/.bin/pm2 start /opt/app/lib/index.js --no-daemon --watch

rabbitmq:
  image: ringpartner/rabbitmq-federation
  environment:
    - PORT=15672
    - CNOSUL_AGENT=1
    - CONSUL=consul
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
  links:
    - consul:consul
  ports:
    - "15672:15672"
  restart: always
