api:
  image: ringpartner/exchange-books
  mem_limit: "256m"
  environment:
    - NODE_PATH=/opt/app/lib
    - CONSUL_AGENT=1
    - CONSUL=exchange-consul.svc.${TRITON_ACCOUNT}.${TRITON_DC}.cns.joyent.com
    - CONSUL_HOST=exchange-consul.svc.${TRITON_ACCOUNT}.${TRITON_DC}.cns.joyent.com
    - PORT=80
    - APP_NAME=books-service
    - APP_VERISON=1.0.0
    - MYSQL_SERVICE=mysql-primary
    - MYSQL_HOST=mysql-primary
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=books
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_SERVICE=rabbitmq
  expose:
    - 80
  ports:
    - 80
  restart: always
  labels:
    - triton.cns.services=exchange-books-api
  command: >
    /bin/containerpilot
    /opt/app/node_modules/.bin/pm2 start /opt/app/lib/index.js --no-daemon --watch
